class moptions:
    create_gif = '1'
    add_watermark = '2'
    export_frame = '3'
    split_video = '4'
    concatenate_video = '5'
    convert_video = '6'
    manipulate_video = '7'
    replace_audio = '8'
    export_audio = '9'